---
title: "vignette_model"
output: html_document
---

```{r setup, include=FALSE}
library(dplyr);library(predictr)
```

```{r}
data <- tibble::as_tibble(survival::colon) %>%
  dplyr::filter(etype==2) %>% # Outcome of interest is death
  dplyr::filter(rx!="Obs") %>%  # rx will be our binary treatment variable
  dplyr::select(-etype,-study, -status) %>% # Remove superfluous variables
  
  # Convert into numeric and factor variables
  dplyr::mutate_at(vars(obstruct, perfor, adhere, node4), function(x){factor(x, levels=c(0,1), labels = c("No", "Yes"))}) %>%
  dplyr::mutate(rx = factor(rx),
                mort365 = cut(time, breaks = c(-Inf, 365, Inf), labels = c("Yes", "No")),
                sex = factor(sex, levels=c(0,1), labels = c("Female", "Male")),
                differ = factor(differ, levels = c(1,2,3), labels = c("Well", "Moderate", "Poor")),
                extent = factor(extent, levels = c(1,2,3, 4), labels = c("Submucosa", "Muscle", "Serosa", "Contiguous Structures")),
                surg = factor(surg, levels = c(0,1), labels = c("Short", "Long")))

data_dev = data %>% head(0.5 * nrow(data))
data_val = data %>% tail(0.5 * nrow(data))
```

1. Development
```{r}
fit <- finalfit::glmmulti(data_dev, dependent = "mort365", explanatory = c("rx", "sex","obstruct", "differ"))

predictr(data = data_dev, fit = fit) %>%
  dplyr::select(event, "predict" = predict_prop)
```
2. Validation (with original model)
```{r}
predictr(data = data_val, fit = fit) %>%
  dplyr::select(event, "predict" = predict_prop)
```

3. Validation (with coefficents only)

```{r}
fit$coefficients

coefficient(fit)
```


Beta 
```{r}
predictr(data = data_val,
         coefficient = coefficient(fit)) %>%
  dplyr::select(event, "predict" = predict_prop)
```

Odds Ratio 

```{r}
predictr(data = data_val,
         coefficient = coefficient(fit, coefficient = "or")) %>%
  dplyr::select(event, "predict" = predict_prop)
```
